import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const sb=createClient(SUPABASE_URL,SUPABASE_ANON_KEY); const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const price=v=>Number(v||0).toLocaleString('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
const quoteTypes=[['usd','USD'],['gold','ORO'],['silver','PLATA']];
let brands=[];
async function loadSettings(){const {data,error}=await sb.from('site_settings').select('*').order('key'); if(error)throw error;const m=Object.fromEntries((data||[]).map(r=>[r.key,r.value]));['whatsapp','hero_title','hero_text','about_text','contact_title','contact_text'].forEach(k=>$(k).value=m[k]||'');}
async function saveSettings(){const keys=['whatsapp','hero_title','hero_text','about_text','contact_title','contact_text'];const rows=keys.map(key=>({key,value:$(key).value.trim()}));const {error}=await sb.from('site_settings').upsert(rows);$('settingsMsg').textContent=error?error.message:'Textos guardados correctamente.';}
async function loadQuotes(){const {data,error}=await sb.from('internal_quotes').select('*').eq('id',1).single();if(error)throw error;['gold_value','silver_value','usd_value'].forEach(k=>$(k).value=data[k]||0);}
async function saveQuotes(){const payload={id:1,gold_value:Number($('gold_value').value||0),silver_value:Number($('silver_value').value||0),usd_value:Number($('usd_value').value||0)};const {error}=await sb.from('internal_quotes').upsert(payload);$('quotesMsg').textContent=error?error.message:'Cotizaciones guardadas. Los precios afectados se recalcularon automáticamente.';if(!error)await refreshStats();}
async function loadBrands(){const {data,error}=await sb.from('brands').select('*').order('sort_order');if(error)throw error;brands=data||[];$('brandsAdmin').innerHTML=brands.map(b=>`<div class="brand-row" data-id="${b.id}"><div class="field"><label>Marca</label><input data-k="name" value="${esc(b.name)}"></div><label class="check"><input data-k="featured" type="checkbox" ${b.featured?'checked':''}> Protagonista</label><label class="check"><input data-k="active" type="checkbox" ${b.active?'checked':''}> Activa</label><div class="row-actions"><button class="button button-dark save-brand">Guardar</button><button class="button button-outline delete-brand">Eliminar</button></div></div>`).join('');document.querySelectorAll('.save-brand').forEach(b=>b.onclick=saveBrand);document.querySelectorAll('.delete-brand').forEach(b=>b.onclick=deleteBrand);}
async function addBrand(){const {error}=await sb.from('brands').insert({name:'Nueva marca',sort_order:999,active:true,featured:false});$('brandsMsg').textContent=error?error.message:'';if(!error)await refresh();}
async function saveBrand(e){const r=e.target.closest('.brand-row'),payload={};r.querySelectorAll('[data-k]').forEach(el=>payload[el.dataset.k]=el.type==='checkbox'?el.checked:el.value.trim());const {error}=await sb.from('brands').update(payload).eq('id',r.dataset.id);$('brandsMsg').textContent=error?error.message:'Marca guardada.';if(!error)await refresh();}
async function deleteBrand(e){const r=e.target.closest('.brand-row');if(!confirm('¿Eliminar esta marca?'))return;const {error}=await sb.from('brands').delete().eq('id',r.dataset.id);$('brandsMsg').textContent=error?error.message:'Marca eliminada.';if(!error)await refresh();}
function productRow(p){const br=brands.map(b=>`<option value="${b.id}" ${p.brand_id===b.id?'selected':''}>${esc(b.name)}</option>`).join('');const imgs=Array.isArray(p.image_urls)?p.image_urls:[];return `<div class="product-row" data-id="${p.id}"><div class="product-head"><div><span class="muted">PRODUCTO</span><h3>${esc(p.name||'Nuevo producto')}</h3></div><span class="price-badge">Precio público: ${price(p.display_price)}</span></div><div class="admin-grid product-fields"><div class="field"><label>Nombre</label><input data-k="name" value="${esc(p.name)}"></div><div class="field"><label>Marca</label><select data-k="brand_id"><option value="">Sin marca</option>${br}</select></div><div class="field"><label>Categoría</label><input data-k="category" value="${esc(p.category||'Relojes')}"></div><div class="field"><label>Stock</label><input data-k="stock" type="number" min="0" step="1" value="${p.stock??0}"></div><div class="field"><label>Sistema de precio</label><select data-k="pricing_type">${quoteTypes.map(([v,l])=>`<option value="${v}" ${p.pricing_type===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field price-config gold-config"><label>Gramos de oro</label><input data-k="gold_grams" type="number" min="0" step="0.0001" value="${p.gold_grams??0}"></div><div class="field price-config silver-config"><label>Gramos de plata</label><input data-k="silver_grams" type="number" min="0" step="0.0001" value="${p.silver_grams??0}"></div><div class="field price-config metal-config"><label>Hechura / adicional</label><input data-k="workmanship" type="number" min="0" step="0.0001" value="${p.workmanship??0}"></div><div class="field price-config usd-config"><label>Base en USD</label><input data-k="usd_base" type="number" min="0" step="0.0001" value="${p.usd_base??0}"></div><div class="field full"><label>Descripción</label><textarea data-k="description">${esc(p.description||'')}</textarea></div><div class="field full"><label>Foto principal (URL o enlace público)</label><input data-k="image_url" value="${esc(imgs[0]||'')}"></div><div class="field full"><label>Subir fotos al catálogo</label><input class="image-upload" type="file" accept="image/*" multiple><small class="small">Podés subir varias perspectivas del mismo producto.</small></div><div class="field"><label>Publicado</label><select data-k="published"><option value="true" ${p.published?'selected':''}>Sí</option><option value="false" ${!p.published?'selected':''}>No</option></select></div><div class="field"><label>Destacado</label><select data-k="featured"><option value="true" ${p.featured?'selected':''}>Sí</option><option value="false" ${!p.featured?'selected':''}>No</option></select></div></div><div class="row-actions"><button class="button button-dark save-product">Guardar</button><button class="button button-outline delete-product">Eliminar</button></div></div>`;}
async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('sort_order');if(error)throw error;$('productsAdmin').innerHTML=(data||[]).map(productRow).join('');document.querySelectorAll('.save-product').forEach(b=>b.onclick=saveProduct);document.querySelectorAll('.delete-product').forEach(b=>b.onclick=deleteProduct);syncPricingVisibility();}
function syncPricingVisibility(){document.querySelectorAll('.product-row').forEach(r=>{const t=r.querySelector('[data-k="pricing_type"]').value;r.querySelector('.gold-config')?.classList.toggle('hidden',t!=='gold');r.querySelector('.silver-config')?.classList.toggle('hidden',t!=='silver');r.querySelector('.metal-config')?.classList.toggle('hidden',t==='usd');r.querySelector('.usd-config')?.classList.toggle('hidden',t!=='usd');});}
async function addProduct(){const {error}=await sb.from('products').insert({name:'Nuevo producto',category:'Relojes',pricing_type:'usd',published:false,featured:false,stock:0,sort_order:999});$('productsMsg').textContent=error?error.message:'';if(!error)await refresh();}
async function saveProduct(e){const r=e.target.closest('.product-row'),payload={};r.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;if(k==='brand_id')payload[k]=el.value||null;else if(['stock'].includes(k))payload[k]=Number(el.value||0);else if(['gold_grams','silver_grams','workmanship','usd_base'].includes(k))payload[k]=Number(el.value||0);else if(['published','featured'].includes(k))payload[k]=el.value==='true';else payload[k]=el.value.trim();});
  const selectedBrand=r.querySelector('[data-k="brand_id"]');
  if(selectedBrand){ const opt=selectedBrand.options[selectedBrand.selectedIndex]; payload.brand=opt?.textContent==='Sin marca'?'':opt?.textContent||''; }
  let image=payload.image_url;delete payload.image_url;
  payload.image_urls=image?[image]:[];const {error}=await sb.from('products').update(payload).eq('id',r.dataset.id);$('productsMsg').textContent=error?error.message:'Producto guardado y precio actualizado.';if(!error)await refresh();}
async function deleteProduct(e){const r=e.target.closest('.product-row');if(!confirm('¿Eliminar este producto?'))return;const {error}=await sb.from('products').delete().eq('id',r.dataset.id);$('productsMsg').textContent=error?error.message:'Producto eliminado.';if(!error)await refresh();}
async function uploadImages(e){
  const input=e.target; const row=input.closest('.product-row'); const id=row?.dataset.id; if(!id||!input.files?.length)return;
  const uploaded=[];
  for(const file of input.files){
    const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');
    const path=`products/${id}/${Date.now()}-${crypto.randomUUID()}-${safe}`;
    const {error}=await sb.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});
    if(error){$('productsMsg').textContent=error.message;return;}
    const {data}=sb.storage.from('product-images').getPublicUrl(path);
    if(data?.publicUrl) uploaded.push(data.publicUrl);
  }
  if(uploaded.length){
    const {data:prod}=await sb.from('products').select('image_urls').eq('id',id).single();
    const current=Array.isArray(prod?.image_urls)?prod.image_urls:[];
    const urls=[...current,...uploaded];
    const {error}=await sb.from('products').update({image_urls:urls}).eq('id',id);
    $('productsMsg').textContent=error?error.message:`${uploaded.length} foto(s) subidas correctamente.`;
    if(!error)await refresh();
  }
}
async function refreshStats(){const [{data:p},{count:pub},{data:b}]=await Promise.all([sb.from('products').select('stock,display_price'),sb.from('products').select('*',{count:'exact',head:true}).eq('published',true),sb.from('brands').select('id,active')]);$('statProducts').textContent=(p||[]).length;$('statPublished').textContent=pub||0;$('statStock').textContent=(p||[]).reduce((a,x)=>a+Number(x.stock||0),0);$('statBrands').textContent=(b||[]).filter(x=>x.active).length;}
async function refresh(){try{await Promise.all([loadSettings(),loadQuotes(),loadBrands(),loadProducts(),refreshStats()]);}catch(e){console.error(e);$('productsMsg').textContent=e.message;}}
function setAuth(s){$('loginCard').classList.toggle('hidden',!!s);$('adminApp').classList.toggle('hidden',!s);}
$('loginBtn').onclick=async()=>{const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('loginMsg').textContent=error?error.message:'';if(!error){setAuth(data.session);await refresh();}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();setAuth(null)};$('refreshBtn').onclick=refresh;$('saveSettings').onclick=saveSettings;$('saveQuotes').onclick=saveQuotes;$('addProduct').onclick=addProduct;$('addBrand').onclick=addBrand;
document.querySelectorAll('.admin-nav button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.admin-nav button').forEach(b=>b.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');$('tab-'+btn.dataset.tab).classList.add('active');});
document.addEventListener('change',e=>{if(e.target.matches('[data-k="pricing_type"]'))syncPricingVisibility();if(e.target.matches('.image-upload'))uploadImages(e);});
const {data:{session}}=await sb.auth.getSession();setAuth(session);if(session)await refresh();
