import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const fallback={settings:{whatsapp:'5491133218175',hero_title:'Piezas para momentos que permanecen.',hero_text:'Joyas y relojes seleccionados con atención personalizada. Descubrí nuestras colecciones y consultanos por tu próxima pieza.',about_text:'M&M nace de Montero & Montero. Desde 1990, la joyería y relojería acompaña a sus clientes con atención personalizada.',contact_title:'¿Ya viste algo que te gustó?',contact_text:'Consultanos por WhatsApp y te ayudamos a encontrar la pieza indicada.'},categories:[{id:'relojes',name:'Relojes',description:'Clásicos, modernos y piezas para todos los días.',class_name:'category-dark',number:'01'},{id:'joyas',name:'Joyas',description:'Detalles para regalar, celebrar o darte un gusto.',class_name:'category-green',number:'02'},{id:'seiko',name:'Seiko',description:'Una sección especial para nuestra marca oficial.',class_name:'category-cream',number:'03'}],products:[]};
const sb=(SUPABASE_URL&&SUPABASE_ANON_KEY)?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const wa=(phone,text)=>`https://wa.me/${String(phone).replace(/\D/g,'')}?text=${encodeURIComponent(text)}`;
async function load(){if(!sb)return fallback;try{const [{data:settings},{data:categories},{data:products}]=await Promise.all([sb.from('site_settings').select('*'),sb.from('categories').select('*').order('sort_order'),sb.from('products').select('*').eq('published',true).order('sort_order')]);const sm=Object.fromEntries((settings||[]).map(x=>[x.key,x.value]));return{settings:{...fallback.settings,...sm},categories:categories?.length?categories:fallback.categories,products:products||[]};}catch(e){console.warn('Supabase no disponible, usando fallback.',e);return fallback;}}
function render(d){const s=d.settings,phone=s.whatsapp||fallback.settings.whatsapp;document.querySelector('#heroTitle').textContent=s.hero_title;document.querySelector('#heroText').textContent=s.hero_text;document.querySelector('#aboutText').textContent=s.about_text;document.querySelector('#contactTitle').textContent=s.contact_title;document.querySelector('#contactText').textContent=s.contact_text;['headerWhatsapp','heroWhatsapp','seikoWhatsapp','contactWhatsapp'].forEach(id=>document.getElementById(id).href=wa(phone,'Hola, quiero consultar por M&M Jewelry.'));document.getElementById('categories').innerHTML=d.categories.map(c=>`<a class="category-card ${esc(c.class_name)}" href="#catalogo"><div><span class="category-kicker">${esc(c.number)}</span><h3>${esc(c.name)}</h3><p>${esc(c.description)}</p></div><span class="arrow">↗</span></a>`).join('');document.getElementById('products').innerHTML=d.products.length?d.products.map(p=>`<article class="product-card"><div class="product-photo">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:`<span>${esc(p.category||'M&M')}</span>`}</div><div class="product-info"><span class="muted">${esc(p.brand||p.category||'Colección')}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${p.price?`<strong class="price">$ ${esc(p.price)}</strong>`:''}<a href="${wa(phone,'Hola, quiero consultar por '+p.name+'.')}" target="_blank" rel="noopener">Consultar →</a></div></article>`).join(''):`<div class="empty-catalog"><span>CATÁLOGO</span><h3>Estamos preparando nuestras piezas.</h3><p>Pronto vas a poder ver el catálogo online de M&M Jewelry.</p></div>`;}
load().then(render);
